// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Gerrymander.Bot.Models
{
    public partial class ResultsBySite
    {
        private string _siteId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string SiteId
        {
            get { return this._siteId; }
            set { this._siteId = value; }
        }
        
        private string _siteName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string SiteName
        {
            get { return this._siteName; }
            set { this._siteName = value; }
        }
        
        private int? _votes;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Votes
        {
            get { return this._votes; }
            set { this._votes = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ResultsBySite class.
        /// </summary>
        public ResultsBySite()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken siteIdValue = inputObject["siteId"];
                if (siteIdValue != null && siteIdValue.Type != JTokenType.Null)
                {
                    this.SiteId = ((string)siteIdValue);
                }
                JToken siteNameValue = inputObject["siteName"];
                if (siteNameValue != null && siteNameValue.Type != JTokenType.Null)
                {
                    this.SiteName = ((string)siteNameValue);
                }
                JToken votesValue = inputObject["votes"];
                if (votesValue != null && votesValue.Type != JTokenType.Null)
                {
                    this.Votes = ((int)votesValue);
                }
            }
        }
    }
}
