// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Gerrymander.Bot.Models;
using Newtonsoft.Json.Linq;

namespace Gerrymander.Bot.Models
{
    public static partial class ResultsByDistrictCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<ResultsByDistrict> DeserializeJson(JToken inputObject)
        {
            IList<ResultsByDistrict> deserializedObject = new List<ResultsByDistrict>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                ResultsByDistrict resultsByDistrict = new ResultsByDistrict();
                resultsByDistrict.DeserializeJson(iListValue);
                deserializedObject.Add(resultsByDistrict);
            }
            return deserializedObject;
        }
    }
}
