// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Gerrymander.ResulstApi.Models;
using Newtonsoft.Json.Linq;

namespace Gerrymander.ResulstApi.Models
{
    public static partial class ResultsByCandidateCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<ResultsByCandidate> DeserializeJson(JToken inputObject)
        {
            IList<ResultsByCandidate> deserializedObject = new List<ResultsByCandidate>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                ResultsByCandidate resultsByCandidate = new ResultsByCandidate();
                resultsByCandidate.DeserializeJson(iListValue);
                deserializedObject.Add(resultsByCandidate);
            }
            return deserializedObject;
        }
    }
}
