// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Gerrymander.ResulstApi.Models
{
    public partial class ResultsByParty
    {
        private string _partyId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PartyId
        {
            get { return this._partyId; }
            set { this._partyId = value; }
        }
        
        private string _partyName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PartyName
        {
            get { return this._partyName; }
            set { this._partyName = value; }
        }
        
        private int? _votes;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Votes
        {
            get { return this._votes; }
            set { this._votes = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ResultsByParty class.
        /// </summary>
        public ResultsByParty()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken partyIdValue = inputObject["partyId"];
                if (partyIdValue != null && partyIdValue.Type != JTokenType.Null)
                {
                    this.PartyId = ((string)partyIdValue);
                }
                JToken partyNameValue = inputObject["partyName"];
                if (partyNameValue != null && partyNameValue.Type != JTokenType.Null)
                {
                    this.PartyName = ((string)partyNameValue);
                }
                JToken votesValue = inputObject["votes"];
                if (votesValue != null && votesValue.Type != JTokenType.Null)
                {
                    this.Votes = ((int)votesValue);
                }
            }
        }
    }
}
