// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Gerrymander.ResulstApi.Models
{
    public partial class ResultsByCandidate
    {
        private string _candidateId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string CandidateId
        {
            get { return this._candidateId; }
            set { this._candidateId = value; }
        }
        
        private string _candidateName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string CandidateName
        {
            get { return this._candidateName; }
            set { this._candidateName = value; }
        }
        
        private int? _votes;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Votes
        {
            get { return this._votes; }
            set { this._votes = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ResultsByCandidate class.
        /// </summary>
        public ResultsByCandidate()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken candidateIdValue = inputObject["candidateId"];
                if (candidateIdValue != null && candidateIdValue.Type != JTokenType.Null)
                {
                    this.CandidateId = ((string)candidateIdValue);
                }
                JToken candidateNameValue = inputObject["candidateName"];
                if (candidateNameValue != null && candidateNameValue.Type != JTokenType.Null)
                {
                    this.CandidateName = ((string)candidateNameValue);
                }
                JToken votesValue = inputObject["votes"];
                if (votesValue != null && votesValue.Type != JTokenType.Null)
                {
                    this.Votes = ((int)votesValue);
                }
            }
        }
    }
}
