// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Gerrymander.ResulstApi.Models
{
    public partial class ResultsByDistrict
    {
        private string _districtId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string DistrictId
        {
            get { return this._districtId; }
            set { this._districtId = value; }
        }
        
        private string _districtName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string DistrictName
        {
            get { return this._districtName; }
            set { this._districtName = value; }
        }
        
        private int? _votes;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Votes
        {
            get { return this._votes; }
            set { this._votes = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ResultsByDistrict class.
        /// </summary>
        public ResultsByDistrict()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken districtIdValue = inputObject["districtId"];
                if (districtIdValue != null && districtIdValue.Type != JTokenType.Null)
                {
                    this.DistrictId = ((string)districtIdValue);
                }
                JToken districtNameValue = inputObject["districtName"];
                if (districtNameValue != null && districtNameValue.Type != JTokenType.Null)
                {
                    this.DistrictName = ((string)districtNameValue);
                }
                JToken votesValue = inputObject["votes"];
                if (votesValue != null && votesValue.Type != JTokenType.Null)
                {
                    this.Votes = ((int)votesValue);
                }
            }
        }
    }
}
